DEL BUILD\SUPAPLEX.OBJ
DEL BUILD\SUPAPLEX.LST
DEL BUILD\SUPAPLEX.MAP
DEL BUILD\SUPAPLEX.EXE


TASM\TASM.EXE /m2 SUPAPLEX.ASM BUILD\SUPAPLEX.OBJ BUILD\SUPAPLEX.LST

TASM\TLINK.EXE BUILD\SUPAPLEX.OBJ
