name: Run OpenSupaplex CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./linux/ci-prepare.sh
          ./linux/ci-build.sh
        shell: bash
      - name: Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux/OpenSupaplex-linux.zip
  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./macos/ci-prepare.sh
          ./macos/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: macos/OpenSupaplex-macOS.zip
  build-vita:
    name: PS Vita
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./vita/ci-docker-run.sh ./vita/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vita-build
          path: vita/build/OpenSupaplex.vpk
  build-switch:
    name: Nintendo Switch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./switch/ci-docker-run.sh ./switch/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: switch-build
          path: switch/OpenSupaplex-switch.zip
  build-psp:
    name: PSP
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./psp/ci-docker-run.sh sh -c "./psp/ci-install-dependencies.sh && ./psp/ci-build.sh"
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: psp-build
          path: psp/OpenSupaplex-psp.zip
  build-ps3:
    name: PS3
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./ps3/ci-docker-run.sh ./ps3/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps3-build
          path: ps3/OpenSupaplex.pkg
  build-wii:
    name: Wii
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./wii/ci-docker-run.sh ./wii/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wii-build
          path: wii/OpenSupaplex-wii.zip
  build-wiiu:
    name: Wii U
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./wiiu/ci-docker-run.sh ./wiiu/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiiu-build
          path: wiiu/OpenSupaplex-wiiu.zip
  build-nds:
    name: Nintendo DS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./nds/ci-docker-run.sh ./nds/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nds-build
          path: nds/OpenSupaplex.nds
  build-3ds:
    name: Nintendo 3DS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./3ds/ci-docker-run.sh ./3ds/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3ds-build
          path: 3ds/OpenSupaplex-3ds.zip
  build-riscos:
    name: RISC OS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenSupaplex
        run: |
          ./riscos/ci-docker-run.sh ./riscos/ci-build.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscos-build
          path: riscos/OpenSupaplex-riscos.zip
  build-windows-x86_64:
    name: Windows x86_64
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: |
          msys2 -c './windows/ci-prepare.sh x86_64'
      - name: Build OpenSupaplex
        run: |
          cd windows
          msys2 -c './ci-build.sh x86_64'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64-build
          path: windows/OpenSupaplex-windows-x86_64.zip
